debian/netmd_wizard.desktop usr/share/applications
debian/icons/16x16/netmd_wizard.png usr/share/icons/hicolor/16x16/apps
debian/icons/24x24/netmd_wizard.png usr/share/icons/hicolor/24x24/apps
debian/icons/32x32/netmd_wizard.png usr/share/icons/hicolor/32x32/apps
debian/icons/48x48/netmd_wizard.png usr/share/icons/hicolor/48x48/apps
debian/icons/64x64/netmd_wizard.png usr/share/icons/hicolor/64x64/apps
debian/icons/128x128/netmd_wizard.png usr/share/icons/hicolor/128x128/apps
res/netmd_wizard.png usr/share/icons/hicolor/256xs256/apps
